### PR TITLE
Ui pieces potential moves

### PR DESCRIPTION
**Pull request by coughenberg**
Allows the user to click on one and only one piece at a time. When a piece is clicked, currently dummy values are sent into the ui to display potential movement places to the piece's left and up directions. Once the user clicks on a piece, they cannot click on another piece. The only way to click on another piece is to click on the piece that was initially clicked on.

MUST MERGE AFTER PR #15 

Good luck

### CODE REVIEW

**Review by mattshoobs — CHANGES_REQUESTED** [review]
resolve conflicts

**Review by PeterX1013 — DISMISSED** [review]
I think I understand, I'll refer to it as I need it and ask you questions when they arise.

**Comment by coughenberg** [comment]
Task linked: [CU-7jf2h4 Add potential movements for piece when picked up](https://app.clickup.com/t/7jf2h4)

**Comment by coughenberg** [comment]
@PeterX1013 Idk how you approved changes lmao

**Comment by PeterX1013** [comment]
LOL! I have no idea... Get your permissions right!

**Review by mattshoobs — APPROVED** [review]
have fun ;)

**Pull request merged**
